name 'device42'
maintainer 'Device42'
maintainer_email 'support@device42.com'
license 'Apache 2.0'
description 'Configure requests to Device42 API'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '1.0.0'
chef_version '>= 14.0'
source_url 'https://github.com/Device42/device42_chef_cookbook'
issues_url 'https://github.com/Device42/device42_chef_cookbook/issues'
